# GitHub Action name
name: Jest automatic testing

# event trigger
on: 
  pull_request:
    branches: 
    - development
    - production

jobs:
  # ID of job
  run-jest-tests:
    # job name
    name: Run Jest tests
    runs-on: ubuntu-latest
    env:
          SECRET_GOOGLE_API_KEY: ${{ secrets.SECRET_GOOGLE_API_KEY }}
          SECRET_HOME_ADDRESS: ${{ secrets.SECRET_HOME_ADDRESS }}
          SECRET_EMAIL_RECEIVER: ${{ secrets.SECRET_EMAIL_RECEIVER }}
          SECRET_EMAIL_SENDER: ${{ secrets.SECRET_EMAIL_SENDER }}
          SECRET_EMAIL_PASS: ${{ secrets.SECRET_EMAIL_PASS }}
          SECRET_EMAIL_SUBJECT: ${{ secrets.SECRET_EMAIL_SUBJECT }}
          SECRET_PASS_POS: ${{ secrets.SECRET_PASS_POS }}
          SECRET_IV_POS: ${{ secrets.SECRET_IV_POS }}
          SECRET_AUTH_USER: ${{ secrets.SECRET_AUTH_USER }}
          SECRET_AUTH_ID: ${{ secrets.SECRET_AUTH_ID }}
          SECRET_AUTH_PASS: ${{ secrets.SECRET_AUTH_PASS }}
          SECRET_PUBLIC_KEY: none
          SECRET_PRIVATE_KEY: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Jest tests
        run: npm run test
        working-directory: ./backend
          
          
